---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "192.168.33.33" }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: app_server
    run_list:
      - recipe[image_rails::app_server]
